### ISSUE TITLE
Get plugins working with a docker install

### ISSUE THREAD

**Issue by Uzay-G** [archivy/archivy-docker#7]
I'm not sure if installing plugins (usually installed via `pip`) works with a docker installation.

CC https://github.com/archivy/archivy-hn/issues/2

Do you know how this could work @Jafner ?

**Comment by Jafner** [comment]
Yeah, you should be able to run a simple `docker exec archivy pip install <plugin>`, although, I think that would only last as long as the container's system volume did. 

I'll test it. Do you have an example plugin I can test with? Something as simple as possible to minimize the possibility that other issues pop up.

**Comment by Uzay-G** [comment]
Maybe this one: https://github.com/archivy/archivy-hn ?

**Comment by ropable** [comment]
For the archivy-hn plugin, installing the plugin fails in the running container due to missing system requirements required to build the lxml wheel ("Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?").

I'm not familiar enough with Alpine myself to test installing that package (indeed I'm not sure that it's even possible in a running Alpine image).

Edit: there are Docker install instructions for the archivy-hn plugin right there on the Github readme, which I failed to notice.

**Comment by Uzay-G** [comment]
Yeah we just added them :)
